### ISSUE TITLE
Codebase modernization: parent issue

### ISSUE THREAD

**Issue by thedotedge** [freelancehunt/fresque#1]
- [x] Set target PHP compatibility: 8.x
- [x] Update dependencies to latest 
- [x] Update PHPUnit https://github.com/webimpress/phpunit-migration
- [x] Remove deprecations and warnings
- [x] Internalize https://github.com/wa0x6e/ResqueStatus into this repo
- [x] Internalize https://github.com/wa0x6e/php-resque-ex-scheduler into this repo
- [x] Internalize https://github.com/wa0x6e/php-resque-ex into this repo
- [x] Cleanup and update readme
- [x] Set up CI builds (CircleCI or Travis?)
- [x] Define release process
- [x] Release 2.0.0
- [ ] Remove Redisent

**Comment by TheMY3** [comment]
> Update PHPUnit
> Set up CI builds (CircleCI or Travis?)

Released here - https://github.com/freelancehunt/fresque/pull/4

> Set target PHP compatibility: 8.x
> Update dependencies to latest
> Remove deprecations and warnings (Except one test)

Released here - https://github.com/freelancehunt/fresque/pull/5

**Comment by TheMY3** [comment]
> Internalize [wa0x6e/ResqueStatus](https://github.com/wa0x6e/ResqueStatus) into this repo

Released here - https://github.com/freelancehunt/fresque/pull/6

**Comment by TheMY3** [comment]
> Internalize https://github.com/wa0x6e/php-resque-ex-scheduler into this repo
Internalize https://github.com/wa0x6e/php-resque-ex into this repo

Released here - https://github.com/freelancehunt/fresque/pull/8
Schedule will not be supported

> Cleanup and update readme

Released here - https://github.com/freelancehunt/fresque/pull/9
